#!/usr/bin/env bash

#COLOR DEFINITIONS
R=$(printf '\033[0;31m')
Y=$(printf '\033[0;33m')
B=$(printf '\033[0;34m')
N=$(printf '\033[0m')
W=$(printf '\033[0;37m')
YB=$(printf '\033[1;33m')

: '
BEHOLD THE GREATEST WATER THAT STARTED ITS LIFETIME JOURNEY BY THE START OF THE HUMANKIND. THE TASTE THAT ONLY CHOSEN MERE INDIVIDUALS EXPERIENCE AT SOME POINT OF THER LIFETIME.
THIS CODE WAS CREATED BY THE HANDS OF ONE OF THE SERVANTS (HelloWorld7894) OF ARO GOD IN THE TIMES OF WISE RULE OF EMPEROR TOMAS THE GREATEST.
10. 08. 2022

cat << EOF
      ${B}n################################################
      ${B}n##########/********#/******#*********###########
      ${B}n##########(/*#*/**(#(***/##(**(###(**(##########
      ${B}n#########(***(//**(#(***###***/###****##########
      ${B}n#########****(****/#(***###****/(****/##########
      ${B}n##########(//(*#(((##(//######/(/(/#######(*.      .
      ${B}n#############################* ,(#################
      n####################, (######################## 
   n###### ########### .############(. 
       (#####/##( /#######/   (
         . ########,
             ,
EOF
'

function get_info(){
	#username, computer, OS, Host, Kernel, Uptime, Packages, Shell, Resolution, DE, WM, WM Theme, Theme, Icons, Terminal, CPU, GPU, Memory
	#some addons -> GPU Driver, Disk, Battery, type, Public IP
	
	if [[ "$OSTYPE" == "linux-gnu" ]]; then
		#linux part
		
		user=$(whoami)
		uptime=$(uptime -p)
	        shell=$SHELL  
		screen=$(xdpyinfo | awk '/dimensions:/ { print $2 }')
                cpu=$(echo $(cat /proc/cpuinfo | grep -m 1 -i 'model name')| cut -d':' -f 2)
	
		audio=$(echo $(lspci | grep -m 1 -i 'Audio device')| cut -d':' -f 3)
		
		network=$(echo $(lspci | grep -m 1 -i 'Network controller')| cut -d':' -f 3)
		
		gpu=$(echo $(lspci | grep -m 1 -i 'VGA compatible controller')| cut -d':' -f 3)		

		if [ -f /etc/os-release ]; then
			. /etc/os-release
			os=$NAME
			kernel=$VERSION_ID
			dist=$ID
		else
			os=$(uname -s)
			kernel=$(uname -r)
			dist="" #I dunno how to check os version the other way
		fi		

		if [[ "$dist" == "arch" || "$dist" == "manjaro" ]]; then # for rolling releases
			# . /proc/sys/kernel/hostname
			host=$(cat /proc/sys/kernel/hostname)

		elif [[ "$dist" == "debian" || "$dist" == "ubuntu" ]]; then #for deb-like releases
			
			host=$(hostname)
	
		else
			

			if (( ${#user} == 0 )); then
				user=$USER
			fi
		fi
		
	else
		echo "ERROR: You have different system other than linux, Weirdo."
	fi
}

#main
get_info

topbar="$user@$host"
topbar_len=${#topbar}

cat << EOF

       ${B}*#################################################################*
       ${B}*################${Y}*(/**/(/(${B}####${Y}//*${B}#${Y}/**${B}(####${Y}*${B}/((((${Y}*${B}#################*
       ${B}*##############${Y}(**********/(${B}#${Y}(********//***********/${B}##############*
       ${B}*##############/(//#${Y}(*(****/${B}#${Y}(****(${B}(##${Y}(****(${B}###${Y}/****/${B}#############*			
       ${B}*##############${Y}(******/****/${B}#${Y}(****(${B}###${Y}/***/${B}#####${Y}/***(${B}#############*			
       ${B}*#############${Y}/***/${B}###${Y}(****/${B}#${Y}(****(${B}###${Y}/****/${B}###${Y}/****/${B}#############*		
       ${B}*#############${Y}/************/${B}#${Y}(****(${B}####${Y}/***********/${B}##############*				
       ${B}*###############${Y}(*//*/#/(/(${B}###${Y}*(*${B}#########/${Y}*(((*${B}(########(*.     ${R} ..,,*  		
       ${B}*##########################################/. ${R}./(####################						
       ${B}*#################################/  ${R}*#############################.						
      ${R}*##( ${B}/######################* ${R}.(#############################(((((.						
${R}, *########## ${B}#############* ${R}.################*									
    ${R}.  *#######,${B}(#####. ${R}/##########(,
         ${R}(  #####, ,########,
               ${R}.######/

${R}________________
${R}|${Y}$topbar
${R}|_______________
${R}|${B}OS:${Y} $os
${R}|${B}Host:${Y} $host
${R}|${B}Kernel:${Y} $kernel
${R}|${B}Uptime:${Y} $uptime
${R}|${B}Shell:${Y} $shell
${R}|${B}Resolution:${Y} $screen
${R}|${B}CPU:${Y} $cpu
${R}|${B}GPU:${Y} $gpu
${R}|${B}Audio device:${Y} $audio
${R}|${B}Network Controller:${Y} $network
${R}|_______________
${YB}You better believe in aro god, it is the only true religion in the whole world

${N}
EOF
